import { defineConfig } from "vite";
import { createReadStream, existsSync, readdirSync, statSync } from "node:fs";
import { extname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = join(here, "html");

/**
 * Every physical page is a Vite HTML entry so the build keeps the same URL
 * shape it is authored with: `index.html`, `products.html`, `admin/...`. The
 * static <link>/<script> references in each page point at the sibling `css/`
 * and `js/` folders, so Vite bundles them, rewrites the hashed assets and
 * leaves the relative routes intact.
 */
function collectEntries(dir) {
  const entries = {};
  for (const file of readdirSync(join(root, dir))) {
    if (!file.endsWith(".html")) continue;
    const abs = join(root, dir, file);
    const key = relative(root, abs).replace(/\.html$/, "").split(sep).join("/");
    entries[key] = abs;
  }
  return entries;
}

const MIME = {
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".woff2": "font/woff2",
};

/**
 * Dev-only: serve the sibling `css/` and `js/` folders.
 *
 * The Vite root is `html/`, so the dev server's URL namespace starts there and a
 * page at `/products.html` asking for `../css/style.css` lands on
 * `/css/style.css` - a path that has no file under the root, and would silently
 * fall through to the `index.html` fallback. The production build is unaffected:
 * it resolves both folders at bundle time and emits hashed assets.
 *
 * Everything the app imports is a relative specifier with an explicit `.js`
 * extension, so the browser can execute these files as plain ES modules without
 * any transformation.
 */
function serveSiblingAssets() {
  return {
    name: "serve-css-and-js-folders",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const [pathname] = (req.url || "").split("?");
        const match = /^\/(css|js)\//.exec(decodeURIComponent(pathname));
        if (!match) return next();

        const base = resolve(here, match[1]);
        const target = resolve(join(here, pathname));
        // Never let a crafted path escape the folder it is served from.
        if (target !== base && !target.startsWith(base + sep)) return next();
        if (!existsSync(target) || !statSync(target).isFile()) return next();

        res.setHeader("Content-Type", MIME[extname(target).toLowerCase()] || "application/octet-stream");
        res.setHeader("Cache-Control", "no-cache");
        createReadStream(target).pipe(res);
      });
    },
  };
}

export default defineConfig({
  root: "html",
  base: "/",
  plugins: [serveSiblingAssets()],
  server: {
    port: 5174,
    // `css/` and `js/` sit next to the Vite root (`html/`), so the dev server
    // has to be told they are part of the project before it will serve them.
    fs: { allow: [here] },
    proxy: {
      "/api": { target: "http://localhost:5050", changeOrigin: true },
      "/uploads": { target: "http://localhost:5050", changeOrigin: true },
    },
  },
  build: {
    // Generated by `npm run build`. Not source: the source of truth for the
    // UI is `html/`, `css/` and `js/`. It is git-ignored.
    outDir: "../dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        ...collectEntries("."),
        ...collectEntries("admin"),
      },
    },
  },
});
